@OrleansPlayground_HostAddress = http://localhost:5032
@BankAccountNumber = abc

GET {{OrleansPlayground_HostAddress}}/account/{{BankAccountNumber}}/deposit/10
Accept: application/json

###

GET {{OrleansPlayground_HostAddress}}/account/{{BankAccountNumber}}/withdraw/3
Accept: application/json

###

GET {{OrleansPlayground_HostAddress}}/account/{{BankAccountNumber}}/balance
Accept: application/json

###

GET {{OrleansPlayground_HostAddress}}/account/{{BankAccountNumber}}/recent
Accept: application/json
